    # Uncomment to copy user public key into user folder in remote machine
  - name: Ensure generation of .ssh folder and hand permissions to remote user
    become: yes
    file:
      path: "/home/{{my_ssh_user.name}}/.ssh"
      state: directory
      owner: "{{my_ssh_user.name}}"
      group: "{{my_ssh_user_group}}"
      mode: 0700

  - name: Ensure upload of SSH key
    become: yes
    copy:
      src: "{{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}}.pub"
      dest:  "/home/vagrant/.ssh/{{my_ssh_user.name}}.pub"
      owner: "{{{{my_ssh_user_key}}"
      group: "{{{{my_ssh_user_key}}"
      mode: 0700