---
- name: Generate EC2 key
  ec2_key:
    name: "{{module_key_name}}"
    region: "{{module_region}}"
  register: myregistered_ec2_keypair

- name: Create folder for EC2 key
  file:
    path: "{{module_keys_dir}}/{{module_region}}"
    state: directory
    mode: 0700
  when: myregistered_ec2_keypair.changed

# copy previously registered ec2_keypair variable
- name: Save key to local machine
  copy:
    content: "{{ myregistered_ec2_keypair.key.private_key }}" 
    dest: "{{module_keys_dir}}/{{module_region}}/{{module_key_name}}.pem"
    mode: 0400
  when: myregistered_ec2_keypair.changed

- name: Generate a public key from the private key
  command: "ssh-keygen -y -f \
          {{module_keys_dir}}/{{module_region}}/{{module_key_name}}.pem"
  args:
    creates: "{{ec2_region}}/{{ec2_key_name}}.pub"
  when: myregistered_ec2_keypair.changed