- name: Remove key pair by name
  ec2_key:
    name: "{{ec2_key_name}}"
    state: absent

- name: Remove SSH key from known hosts
  command: "ssh-keygen -R api.{{route53.record.subDNS}}.{{route53.zone.DNS}}"

- name: Delete keys from local machine
  file:
    state: absent
    path: "{{ec2_keys_dir}}/{{ec2_region}}"