---
- name: Check if EC2 keys are present on machine
  stat:
    path: "{{ec2_keys_dir}}/{{ec2_region}}/{{ec2_key_name}}.pem"
  register: file_stat

- name: If absent, ensure EC2 key directory is created
  file:
    path: "{{ec2_keys_dir}}/{{ec2_region}}"
    state: directory
    mode: 0700
  when: file_stat.stat.exists == false

- name: Download the ec2_key. If absent, create it then download it.
  block:
    # download the ec2_keys
    - include_tasks: roles/aws/tasks/mng_ec2_keys/download.yml
      tags:
        - fetch-key
  rescue:
    # if failed, then create the keys and upload the keys
    - include_tasks: roles/aws/tasks/create_environment.yml
      tags:
        - fetch-key
  always:
    #  now redo the download
    - include_tasks: roles/aws/tasks/mng_ec2_keys/download.yml
      tags:
        - fetch-key
        
- name: Remove URL from known_hosts
  known_hosts:
    name: "api.{{cluster.name}}"
    state: absent

# Change key permissions
- file:
    path: "{{ec2_keys_dir}}/{{ec2_region}}/{{ec2_key_name}}.pem"
    mode: 0600

- file:
    path: "{{ec2_keys_dir}}/{{ec2_region}}/{{ec2_key_name}}.pub"
    mode: 0600