---
#  NOTE: Be sure to allow access to the port first, before rate limiting

  # ufw supports connection rate limiting, which is useful for protecting
  # against brute-force login attacks. ufw will deny connections if an IP
  # address has attempted to initiate 6 or more connections in the last
  # 30 seconds. See  http://www.debian-administration.org/articles/187
  # for details. Typical usage is:
  - name: Ensure OpenSSH rate limiting and log it
    become: yes
    ufw:
      rule: limit
      port: ssh
      proto: tcp
      log: yes