---
   # Uncomplicated firewall(ufw) comes out-of-the-box with ubuntu xenial
  - name: Ensure UFW is Installed
    become: "{{remote_controller_user}}"
    package:
      name: ufw
      state: present
  
  - name: UFW settings
    block:
    - name: Ensure ufw logs
      ufw:
        logging: on