---
   # Uncomplicated firewall(ufw) comes out-of-the-box with ubuntu xenial
  - name: Ensure UFW is Installed
    become: yes
    package:
      name: ufw
      state: present
  
  - name: Ensure UFW settings are set
    become: yes
    ufw:
      logging: on