---
- name: Add the ebs block to the nodes in the terraform
  blockinfile:
    path: roles/terraform/files/kubernetes.tf
    insertafter: 'resource "aws_launch_configuration" "nodes-{{route53.record.subDNS}}.{{route53.zone.DNS}}"'
    marker: "##### {mark} ANSIBLE MANAGED BLOCK (EBS PROVISION)####"
    backup: yes
    content: |
          ebs_block_device {
            device_name           = "{{cluster_accessories.spare_device1.device_fullname}}"
            volume_size           = "{{cluster_accessories.spare_device1.volume_size}}"
            volume_type           = "{{cluster_accessories.spare_device1.volume_type}}"
            delete_on_termination = "{{cluster_accessories.spare_device1.delete_on_termination}}"
          }
