---
# Run and log output of command into file
- name: Set the name of the file
  set_fact:
    mysetfact_module_cmdlogfile: "{{module_file}}"

- include: roles/common/tasks/create_directory.yml
  vars: 
    module_path: "{{mysetfact_module_cmdlogfile}}"

- include: roles/common/tasks/create_file.yml
  vars: 
    module_path: "{{mysetfact_module_cmdlogfile}}"

- include: roles/common/tasks/command_log/template.yml
  vars:
    module_command: "{{item.command}}"
    module_command_aim: "{{item.aim}}"
    module_cmdlogfile: "{{mysetfact_module_cmdlogfile}}"
  with_items: "{{module_command_array}}"

- name: Open the log in browser page {{mysetfact_module_cmdlogfile}}
  command: "firefox {{mysetfact_module_cmdlogfile}}"