---
# Run and log output of command into file
- name: Set the name of the file
  set_fact:
    mysetfact_module_cmdlogfile: "{{module_file}}"

- include_tasks: roles/common/tasks/create_directory.yml
  vars: 
    module_path: "{{mysetfact_module_cmdlogfile}}"

- include_tasks: roles/common/tasks/create_file.yml
  vars: 
    module_path: "{{mysetfact_module_cmdlogfile}}"

- include_tasks: roles/common/tasks/command_log/template.yml
  vars:
    module_become: "{{module_command_become}}"
    module_command: "{{item.command}}"
    module_command_aim: "{{item.aim}}"
    module_cmdlogfile: "{{mysetfact_module_cmdlogfile}}"
  with_items: "{{module_command_array}}"
# 
#/....,..........example usage,,,,,,,,,,,,,,
# - include_tasks: roles/common/tasks/command_log/main.yml
#   vars:
#     module_file: "{{role_path}}/files/logs/{{ansible_date_time.iso8601}}.log.html"
#     module_command_array:
#       - {command: "kubectl get nodes", aim: "fetching nodes"}
#       - {command: "kubectl list cluster", aim: "listing clusters"}
#       - {command: "kubectl get cs", aim: "checking cluster health (component status)"}
#       - {command: "kubectl get pods", aim: "fetching pods"}
#       - {command: "kubectl get deployments", aim: "fetching deployments"}
#       - {command: "kubectl config view", aim: "check current config"}
#       - {command: "kubectl cluster-info", aim: "cluster info"}
#   tags:
#     - cluster-checks

- name: Open the log in browser page {{mysetfact_module_cmdlogfile}}
  command: "firefox {{mysetfact_module_cmdlogfile}}"