---
#  -----------------------------------aws.credentials-------------------------------------
# Ensure credentials exists in desired profile
  # Get the aws credentials currently configured if profile cannot be found
- include_tasks: roles/aws/tasks/mng_credentials/get_current_cred.yml

# Fetch file
- name: Set fact with name
  set_fact:
    mysetfact_aws_credentials_file: "{{item}}"
  with_first_found: 
    - file: "{{aws.credentials.file_precedence}}"
      skip: true

  # Ensure aws.config exists and contains desired profile (don't override profile)
- include: roles/common/tasks/mng_config_file/add.yml
  vars:
    common_module_config_file: "{{mysetfact_aws_credentials_file | default(aws.credentials.file_precedence[0])}}"
    common_module_config_add_become: no
    common_module_config_add_section: "{{my_env}}"
    common_module_config_override: no # 'no': only sets option IFF blank or not existing
    common_module_config_add_settings:
      - { option: aws_access_key_id, value: "{{mysetfact_AWS_ACCESS_KEY_ID}}"}
      - { option: aws_secret_access_key, value: "{{mysetfact_AWS_SECRET_ACCESS_KEY}}"}
     
#  -----------------------------------aws.config--------------------------------------------
#  Ensure aws.config exists and contains desired profile (don't override profile)
- include: roles/common/tasks/mng_config_file/add.yml
  vars:
    common_module_config_file: "{{aws.config.file}}"
    common_module_config_add_become: no
    common_module_config_add_section: "{{my_env}}"
    common_module_config_override: no # 'no': only sets option IFF blank or not existing
    common_module_config_add_settings:
      - { option: region, value: "{{mysetfact_REGION}}"}
      - { option: output, value: "{{mysetfact_OUTPUT}}"}