---
- name: Search for aws credential profile otherwise, create one
  block:
    - debug:
        msg: "ini is {{lookup('ini', 'section=aws_access_key_id file={{file_to_use}} section={{lookup ('first_found',dict(boto_conf_credentials_section_precedence))}}"
      with_first_found: 
        - file: "{{aws_boto_config_file_precedence}}"
      loop_control:
        loop_var: file_to_use
      register: register_cmd
    - debug:
        msg: "register_cmd is {{register_cmd.results}}"
  rescue:
    - debug:
        msg: "in rescue"
    - include_tasks: roles/aws/tasks/mng_credentials/create_boto_profile.yml
  tags:
    - dynamic
    - gluster-create
