---
#  Ensure AWS keys are configured on the system
############################
# Setup iam_user for AWS
############################
- name: Ensure iam user is created and added to group
  iam:
    iam_type: user
    name: "{{ module_iam_user }}"
    groups: "{{ module_iam_groups }}" 
    access_key_state: remove
    state: absent