---
- name: Deploy tiler service account
  block:
  - name: "Ensure tiller service account is prepared"
    become: false
    template:
      src: "{{role_path}}/template/tiller_namespace_sa.yaml.j2"
      dest: "{{helm_deployment_path}}/tiller_namespace_sa.yaml"
      mode: 0644

  - name: "Ensure tiller service account is deployed"
    command: "kubectl apply -f {{helm_deployment_path}}/tiller_namespace_sa.yaml"