---
# Author: Olaolu Akinsete<akinsbo@gmail.com>
# Date: May 16, 2018<3:46am>
###########################
## Setup remote controller
###########################

- hosts: "{{controller | default('localhost')}}"
  connection: local
  gather_facts: false
  roles:
    - controller
