---
# Author: Olaolu Akinsete<akinsbo@gmail.com>
# Date: May 16, 2018<3:46am>
###########################
## Install kubectl and kops
###########################

- hosts: localhost
  connection: local
  roles:
    - kops
