
- hosts: master # bastion.k8s.maryboye.org # tag_Name_bastions_k8s_maryboye_org #bastion.k8s.maryboye.org # #"{{bastion.inventory_group}}"
  connection: ssh
  become: admin
  gather_facts: no

  pre_tasks:

    - setup:
    
    - name: Ping
      ping: ~

  roles:
    - glusterfs
    # - name: run inventory command
    #   command: "{{inventory_dir}}/ec2.py"
    #   # args:
    #     # chdir: "{{inventory_dir}}"