---
- hosts: "{{cluster_supplemental_group | default('cluster_servers')}}"  # bastion.k8s.maryboye.org # tag_Name_bastions_k8s_maryboye_org #bastion.k8s.maryboye.org # #"{{bastion.inventory_group}}"
  connection: ssh
  become: "{{cluster.image_root_user}}"
  gather_facts: no

  pre_tasks:

    - setup:
    
    - name: Ping
      ping: ~

    # - debug:
    #     msg: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

    # - debug:
    #     msg: "{{hostvars[inventory_host].ec2_block_devices]}}"
  
    # - meta: end_play  
  roles:
    - glusterfs
    # - name: run inventory command
    #   command: "{{inventory_dir}}/ec2.py"
    #   # args:
    #     # chdir: "{{inventory_dir}}"