---
# Author: Olaolu Akinsete<akinsbo@gmail.com>
# Date: May 16, 2018<3:46am>
###########################
## Install kubectl and kops
###########################

- hosts: localhost
  connection: local
  
  pre_tasks:
    # set aws_avail_zone variable (for use in kops-create zone and master-zone args)
    - include: roles/aws/tasks/get_availability_zone/main.yml
      vars:
        module_get_avail_region: "{{ ec2_region }}"
      tags:
        - avail
        - create
        
    - name: number_of_zones
      pause:
        prompt: "There are {{mysetfact_num_aws_avail_zone}} zones in this region, namely: {{mysetfact_aws_avail_zone}}. Set vars for zones to deploy in else [ALL] zones would be used?" 
  
  roles:
    # - aws
    - kops
    - terraform
