---
# Author: Olaolu Akinsete<akinsbo@gmail.com>
# Date: May 16, 2018<3:46am>
###########################
## Install kubectl and kops
###########################

- hosts: localhost
  connection: local
  gather_facts: no

  pre_tasks:
    - include_tasks: roles/terraform/tasks/update_tf/update_creds_profile.yml
        
    - setup:

    - include_tasks: roles/aws/tasks/mng_inventory/dynamically_populate.yml
      vars:
        aws_module_inventory_description: "{{item.description}}"
        aws_module_inventory_group: "{{item.group}}"
      with_items:
        - { description: "Bastion group", group: "[{{kops_bastion_inventory_group}}]"}        
        - { description: "Node group", group: "[{{kops_node_inventory_group}}]"}
        - { description: "Master group", group: "[{{kops_master_inventory_group}}]"}
      tags:
        - test_env
    
    - include: script
      script: /
      
    - meta: end_play

    # Set environmental variable
    - include_tasks: roles/terraform/tasks/mng_env/set.yml

    - include_tasks: roles/aws/tasks/get_availability_zone/main.yml
      tags:
        - avail
        - create
        
    # - name: number_of_zones
    #   pause:
    #     prompt: "There are {{mysetfact_num_aws_avail_zone}} zones in this region, namely: {{mysetfact_aws_avail_zone}}. Set vars for zones to deploy in else [ALL] zones would be used?" 

  roles:
    - kops
    - terraform
    - glusterfs
    - k8s
