---
#  list out dynamic inventory
- include_tasks: roles/aws/tasks/mng_inventory/list.yml
  vars:
    aws_module_inventory_list_group: 127.0.0.1

- include_tasks: roles/aws/tasks/mng_inventory/insert.yml
  vars:
    aws_module_inventory_insert_group: "{{aws_module_inventory_group}}"
    aws_module_inventory_insert_description: "{{aws_module_inventory_description}}"
  
- include_tasks: roles/aws/tasks/mng_inventory/list.yml
  vars:
    aws_module_inventory_list_group: "{{aws_module_inventory_group}}"

#################################
# vars:
#   aws_module_inventory_description:
#   aws_module_inventory_group: