---
- debug:
    msg: "ssh -i {{cluster.ssh_private_key}} root@172.20.63.35"   
  tags:
    - debug_ssh
    - gluster-create

# prepare credentials
- include_tasks: roles/aws/tasks/mng_credentials/create_boto_profile.yml
  tags:
    - debug_ssh
    - gluster-create

- name: Make ec2.py and private key executable
  file: 
    path: "{{item}}"
    mode: "ugo+x"
  with_items:
    - "{{ec2_py_path}}"
    - "{{cluster.ssh_private_key}}"
  tags:
    - gluster-create

#  list out dynamic inventory
- include_tasks: roles/common/tasks/command_log/main.yml
  vars:
    module_command_become: no
    module_file: "{{playbook_dir}}/log/temp/inventory_list"
    module_command_array:
      - {command: "{{playbook_dir}}/inventory/ec2.py --boto-profile prod", aim: "List out dynamic inventory"}
  # delegate_to: 127.0.0.1
  tags:
    - gluster-create

- name: Insert {{module_description}} into inventory
  lineinfile:
    path: "{{inventory_file}}"
    line: "{{module_line}}"
    state: present 
  tags:
    - gluster-create