---
- name: "Insert {{aws_module_inventory_insert_description}} into inventory"
  blockinfile:
    path: "{{inventory_file}}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{aws_module_inventory_insert_group}}"
    state: present 
    content: |

      [{{aws_module_inventory_insert_group}}]

      [{{aws_module_inventory_insert_group}}:vars]
      ansible_connection=ssh
      ansible_ssh_private_key_file={{cluster.ssh_private_key}}
      ansible_ssh_common_args = '-o IdentitiesOnly=yes'
      ansible_user = admin

  tags:
    - gluster-create

# vars:
#   aws_module_inventory_insert_group:
#   aws_module_inventory_insert_description: 