---
- debug:
    msg: "ssh -i {{cluster.ssh_private_key}} root@172.20.63.35"   
  tags:
    - debug_ssh

- name: Make ec2.py and private key executable
  file: 
    path: "{{item}}"
    mode: "ugo+x"
  with_items:
    - "{{ec2_py_path}}"
    - "{{cluster.ssh_private_key}}"

#  set aws credentials in boto profile from .env
#  Ensure ~/boto exists
- include_tasks: roles/common/tasks/create_file.yml
  vars:
    module_path: "{{lookup('env', 'HOME')}}/boto"

# set the inifile settings
  - name: Ensure aws credentials in boto profile from .env
  ini_file:
    path: "{{lookup('env', 'HOME')}}/boto"
    section: "profile_{{ environment }}" #e.g. profile_prod
    option: "{{item.option}}"
    value: "{{item.value}}"
    mode: 0600
    backup: yes
  with_items:
    - { option: aws_access_key_id, value: lookup('env', 'AWS_KEY_ID')}
    - { option: aws_secret_access_key, value: lookup('env', 'AWS_SECRET_KEY')}

#  list out dynamic inventory
- include_tasks: roles/common/tasks/command_log/main.yml
  vars:
    module_command_become: yes
    module_file: "{{playbook_dir}}/log/temp/inventory_list.log.html"
    module_command_array:
      - {command: "{{playbook_dir}}/inventory/ec2.py --list", aim: "List out dynamic inventory"}
  delegate_to: 127.0.0.1

- name: Insert {{module_description}} into inventory
  lineinfile:
    path: "{{inventory_file}}"
    line: "{{module_line}}"
    state: present
    
