---
# create credentials profile if not created
- include_tasks: roles/aws/tasks/mng_credentials/create_profile.yml
  tags:
    - debug_ssh
    - gluster-create

- name: Make ec2.py and private key executable
  file: 
    path: "{{item}}"
    mode: "ugo+x"
  with_items:
    - "{{ec2_py_path}}"
    - "{{cluster.ssh_private_key}}"
  tags:
    - gluster-create
