---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio
  labels:
    k8s-app: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: istio
  namespace: istio-system
