---
# set aws_avail_zone variable (for use in kops-create zone and master-zone args)

- set_fact:
    mysetfact_create_command: "kops create cluster {{ cluster.name }} \
                                --cloud aws \
                                --ssh-public-key {{cluster.ssh_public_key}} \
                                --master-count {{cluster.num_of_master}} \
                                --node-count {{ cluster.num_of_nodes }} \
                                --zones {{ cluster.zones | default(mysetfact_aws_avail_zone, true) }} \
                                --master-zones {{ cluster.master_zones | default(mysetfact_aws_avail_zone, true) }} \
                                --node-size {{ cluster.ec2_node_type }} \
                                --master-size {{ cluster.ec2_master_type }} \
                                --state {{ state_store }} \
                                --cloud-labels 'Team=Dev,Owner={{iam.user.name}}' \
                                {% if cluster.bastion == True %}
                                --bastion \
                                --topology {{cluster.topology}} \
                                --networking {{cluster.networking}}
                                 {% endif %}
                                --out {{cluster.output_location}} \
                                --target {{cluster.output_file_type}}"


- block:
    - name: "Build cluster configuration in zone {{ mysetfact_aws_avail_zone }}"
      command: "{{ mysetfact_create_command }}"
    # register: myregistered_cluster_cmd
  rescue:
    - include_tasks: delete_cluster.yml
    
    - name: "Try to create the cluster again"
      command: "{{ mysetfact_create_command }}"