---
#  Ensure the temp directory exists
- include_tasks: roles/common/tasks/create_dir.yml
  vars:
    common_dir_module_path: "{{role_path}}/files/tmp"

- name: Ensure AWS cluster k8s manifest is created for cluster
  command: "kops get cluster {{ cluster.name }} \
                                --state={{state_store}} \
                                --output yaml \
                                > {{role_path}}/files/tmp/manifest_{{ cluster.name }}.yaml"

- name: Ensure FULL AWS cluster k8s manifest is created for cluster
  command: "kops get cluster {{ cluster.name }} \
                                --full \
                                --state={{state_store}} \                                
                                --output yaml \
                                > {{role_path}}/files/tmp/manifest_{{ cluster.name }}.full.yaml"