---
##############
# Install Kubectl
##############
- name: Ensure gathering of facts
  setup:
  tags:
    - install-kops
  when: ansible_os_family is undefined

- name: Download and install kubectl for darwin os
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{item.package}}"
    owner: "{{local_ansible_user}}"
    group: "{{local_ansible_group}}"
    mode: 0755
    force: yes
    # TODO Add hash check
  with_items:
    - {package: kubectl, url: "{{ kubectl_darwin_download_path }}"}
    - {package: kops, url: "{{ kops_darwin_download_path }}"}
  when: ansible_os_family == 'Darwin'
  tags: 
    - install-kops

- name: Download and install kubectl for linux and others
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{item.package}}"
    owner: "{{local_ansible_user}}"
    group: "{{local_ansible_group}}"
    mode: 0755
    force: yes
    # TODO Add hash check
  with_items:
    - {package: kubectl, url: "{{ kubectl_download_path }}"}
    - {package: kops, url: "{{ kops_download_path }}"}
  when: ansible_os_family != 'Darwin'
  tags: 
    - install-kops