---
#############################
# Install Kubectl & Kops
#############################
- include_tasks: roles/common/tasks/download_pkg.yml
  vars:
    module_package: kubectl
    module_darwin_url: "{{ kubectl_darwin_download_path }}"
    module_linux_url: "{{ kubectl_download_path }}"
  tags:
    - instal-kubectl 
    - install-kops

- include_tasks: roles/common/tasks/download_pkg.yml
  vars:
    module_package: kops
    module_darwin_url: "{{ kops_darwin_download_path }}"
    module_linux_url: "{{ kops_download_path }}"
  tags: 
    - install-kops