---
############################
# Install Kubectl and kops
############################
# Download and install kubectl for OSX users
- include: roles/common/tasks/download_pkg
  become: true
  vars:
    module_file_name: "{{ package }}"
    module_dest_folder: "/usr/local/bin/{{item.package}}"
    module_file__owner: "{{local_ansible_user}}"
    module_file__owner_group: "{{local_ansible_group}}"
  with_items:
    - {package: kubectl, url: "{{ kubectl_darwin_download_path }}"}
    - {package: kops, url: "{{ kops_darwin_download_path }}"}
  when: ansible_os_family == 'Darwin'
  tags:
    - kubectl
    - kops
  
  # Download and install kubectl for linux and others
- include: roles/common/tasks/download_pkg
  become: true
  vars:
    module_file_name: "{{ package }}"
    module_dest_folder: "/usr/local/bin/{{item.package}}"
    module_file__owner: "{{local_ansible_user}}"
    module_file__owner_group: "{{local_ansible_group}}"
  with_items:
    - {package: kubectl, url: "{{ kubectl_download_path }}"}
    - {package: kops, url: "{{ kops_download_path }}"}
  when: ansible_os_family != 'Darwin'
  tags:
    - kubectl
    - kops