---
# - include_tasks: install-kubectl-kops.yml
- include_tasks: roles/aws/tasks/mng_iam/group/create.yml
  vars:
    module_iam_group: "{{ iam.user.groups }}"    
  tags:
    - iam
    - iam_group
    - iam_user
    - create
    - kops-create

- include_tasks: roles/aws/tasks/mng_iam/group/attach_policies.yml
  vars:
    module_iam_group: "{{ iam.user.groups }}"
    module_group_policy: "{{ item }}"
  with_items: "{{ kops_aws_managed_policies }}" 
  tags:
    - iam_group
    - iam_group_policy
    - create
    - kops-create
  run_once: true
  
- include_tasks: roles/aws/tasks/mng_iam/user/create.yml
  vars:
    module_iam_user: "{{ iam.user.name }}"
    module_iam_groups: "{{ iam.user.groups }}"
  tags:
    - iam
    - iam_user
    - create
    - kops-create
  run_once: true

- include_tasks: roles/aws/tasks/mng_s3_bucket/create.yml
  vars:
    module_bucket_name: "{{ state_store | replace('s3://', '') }}"
    module_bucket_region: "{{ ec2_region }}"
    module_bucket_tags: "{{ s3_bucket_tags }}"
  tags:
    - create
    - kops-create

- include_tasks: roles/aws/tasks/mng_ec2_keys/fetch_if_unavailable.yml
  tags:
    - create
    - kops-create
    - kops-fetch-keys

- include_tasks: create_cluster.yml
  tags:
    - create
    - kops-create

- include_tasks: export_cluster_config.yml
  tags:
    - create
    - kops-create
    - config

- include_tasks: export_cluster_manifest.yml
  tags:
    - create
    - kops-create
    - get-manifest
    - config
    
# - include_tasks: apply_cluster_creation.yml
#   tags:
#     - create
#     - kops-create

- include_tasks: delete_cluster.yml
  tags:
    - destroy
    - kops-destroy
  