---
# - include_tasks: install-kubectl-kops.yml
- include_tasks: group/create.yml
  vars:
    module_iam_group: "{{ iam.user.groups }}"    
  tags:
  - iam
  - iam_group
  - iam_user

- include_tasks: group/attach_policies.yml
  vars:
    module_iam_group: "{{ iam.user.groups }}"
    module_group_policy: "{{ item }}"
  with_items: "{{ kops_aws_managed_policies }}" 
  tags:
    - iam_group
    - iam_group_policy  
  run_once: true
  
- include: roles/aws/tasks/mng_iam/user/create.yml
  vars:
    module_iam_user: "{{ iam.user.name }}"
    module_iam_groups: "{{ iam.user.groups }}"
  tags:
    - iam
    - iam_user
  run_once: true

- include_tasks: roles/aws/tasks/mng_s3_bucket/create.yml
  vars:
    module_bucket_name: "{{ state_store | replace('s3://', '') }}"
    module_bucket_region: "{{ ec2_region }}"
    module_bucket_tags:
      Name: "{{ state_store | replace('s3://', '') }}"
      Creator: "{{ tag_creator }}"
      Owner: "{{ tag_owner }}"
      Application: "{{ tag_application }}"
      CostCenter: "{{ tag_costcenter }}"
      Confidentiality: "{{ tag_confidentiality }}"
      Environment: "{{ tag_environment }}"

- include: roles/aws/tasks/mng_ec2_keys/fetch_if_unavailable.yml
  tags:
    - create
    - kops-create
    - kops-fetch-keys

- include: create_cluster.yml
  tags:
    - create
    - kops-create

- include: apply_cluster_creation.yml
  tags:
    - create
    - kops-create

- include: delete_cluster.yml
  tags:
    - destroy
    - kops-destroy
  