---
# - include_tasks: install-kubectl-kops.yml
# - include_tasks: setup-aws-user.yml
- include_tasks: group/create.yml
  vars:
    iam_group: "{{ iam.user.groups }}"    
  tags:
  - iam
  - iam_group
  - iam_user

- include_tasks: group/setup-policies.yml
  vars:
    iam_group: "{{ iam.user.groups }}"  
  tags:
    - iam_group
    - iam_group_policy  
  run_once: true
  
- include: roles/aws/tasks/mng_iam/user/create.yml
  vars:
    iam_user: "{{ iam.user.name }}"
    iam_groups: "{{ iam.user.groups }}"
  tags:
    - iam
    - iam_user
  run_once: true

- include_tasks: roles/aws/tasks/mng_s3_bucket/create.yml
  vars:
    bucket_name: "{{ state_store | replace('s3://', '') }}"
    bucket_region: "{{ ec2_region }}"
    bucket_tags:
      Name: "{{ state_store | replace('s3://', '') }}"
      Creator: "{{ tag_creator }}"
      Owner: "{{ tag_owner }}"
      Application: "{{ tag_application }}"
      CostCenter: "{{ tag_costcenter }}"
      Confidentiality: "{{ tag_confidentiality }}"
      Environment: "{{ tag_environment }}"

- include_tasks: create-cluster.yml

  