---
- name: Ensure directory exists
  file:
    path: "{{role_path}}/files"
    state: directory

- name: Ensure Istio values file is generated
  template:
      dest: "{{role_path}}/files/values.yml" 
      src: "{{role_path}}/templates/values.yml.j2" 

# helm install install/kubernetes/helm/istio --name istio --namespace istio-system
- include_tasks: roles/helm/tasks/mng_pkg/install.yml
  vars:
    helm_module_pkg_name: istio
    helm_module_pkg_repo: incubator
    helm_module_pkg_namespace: istio-system
    helm_module_pkg_version: 0.2.13-chart4
    helm_module_pkg_values_file: "{{role_path}}/files/values.yml"