---
############################
# Delete the S3 bucket for the Kops state store
############################
- name: Ensure a S3-Bucket is created
  s3_bucket:
    name: "{{ bucket_name }}"
    region: "{{ bucket_region }}"
    state: absent