
---
- name: "Get all availability zones from aws for region {{ ec2_region }}"
  command: "aws ec2 describe-availability-zones --region {{ ec2_region }} --filters Name=state,Values=available"
  register: myregistered_aws_cmd

- name: Register the zones as an environment variable
  set_fact:
    mysetfact_aws_avail_zone: "{{ myregistered_aws_cmd.stdout|from_json|json_query('AvailabilityZones[].ZoneName')|join(',') }}"

- name: Register number of available zones as an environment variable
  set_fact:
    mysetfact_num_aws_avail_zone: "{{(myregistered_aws_cmd.stdout|from_json).AvailabilityZones | length}}"