---
- name: Get nodes
  shell: "kubectl get nodes | grep {{k8s_module_inventory_group}} | grep -oP 'ip-\\K(\\S*)(?=.eu-west-1.compute.internal)'"
  register: myregistered_list
  tags:
    - get_nodes
  
# - debug: 
#     var: myregistered_list.stdout

- name: insert group into host file
  become: yes
  blockinfile:
    path: "{{inventory_dir}}/hosts"
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{k8s_module_inventory_group}}"
    block: |

      [{{k8s_module_inventory_group}}]
      {{myregistered_list.stdout | regex_replace('-', '.')}}