---
- include_tasks: roles/common/tasks/cmd_log/main.yml
  vars:
    common_module_cmd_log_file: "{{role_path}}/files/logs"
    common_module_cmd_log_command_become: no
    common_module_cmd_log_command_array:
      - {command: "kubectl get nodes", aim: "fetching nodes"}
      - {command: "kubectl list cluster", aim: "listing clusters"}
      - {command: "kubectl get cs", aim: "checking cluster health (component status)"}
      - {command: "kubectl get pods", aim: "fetching pods"}
      - {command: "kubectl get deployments", aim: "fetching deployments"}
      - {command: "kubectl config view", aim: "check current config"}
      - {command: "kubectl cluster-info", aim: "cluster info"}
  tags:
    - cluster-checks