---
- name: Ensure the cluster-admin role-binding definition is prepared
  template:
    src: "cluster-admin-rb-sa.yaml.j2"
    dest: "{{role_path}}/files/tmp/{{k8s_module_sa}}/cluster-admin-rb-sa-{{k8s_module_sa}}.yaml"
  vars: 
    k8s_module_template_cluster_sa: "{{k8s_module_sa}}"
    k8s_module_template_cluster_namespace: "{{k8s_module_namespace | default(kube-system)}}"
    
- name: |
          Ensure the service account is created
          in kube-system namespace 
          and cluster-bound to the cluster-admin role
  command: "kubectl apply -f {{role_path}}/files/tmp/{{k8s_module_sa}}/cluster-admin-rb-sa-{{k8s_module_sa}}.yaml"
################################################
# vars:
#   k8s_module_sa:  # e.g. kubernetes-dashboard
#   k8s_module_namespace: #optional

    