---
- include_tasks: roles/k8s/tasks/checks/wait_for_cluster.yml

- include_tasks: roles/k8s/tasks/mng_addons/main.yml
  tags:
    - k8s
    - addons
    - dashboard

# - name: Run proxy command to serve dashboard
#   command: kubectl proxy
#   tags:
#     - k8s
#     - addons
#     - dashboard

# Ensure checks are run
- include_tasks: roles/k8s/tasks/checks/main.yml
  tags:
    - k8s
    - cluster-checks
