---
# tasks file for k8s
- include: mng_addons/dashboard/main.yml
  tags:
    - k8s
    - addons
    - dashboard

- name: Run proxy command to serve dashboard
  command: kubeclt proxy
  tags:
    - k8s
    - addons
    - dashboard