---
- name: Ensure option exists
  block:
  - name: "Check if env var exists in {{common_module_config_setting_file}}"
    command: "grep '^{{common_module_config_setting_section | default(common_module_config_settings[0].option)}}' {{common_module_config_setting_file}}"
    ignore_errors: yes
    register: myregistered_grep_output

  - name: If option does not exist add it
    become: "{{common_module_config_setting_become}}"
    lineinfile:
      path: "{{common_module_config_setting_file}}" 
      state: present
      line: "{{item.option}}={{item.value}}" 
    with_items: "{{common_module_config_settings}}"   
    when: myregistered_grep_output.rc == 1


# ====================================================================================
# vars:
#   common_module_config_file:
#   common_module_config_setting_become: 
#   common_module_config_setting_section:
#   common_module_config_settings:
#     - {option: abc, value: xyz}