---
# group_vars/all/vars.yml
app_name: mbshow
app_full_name: The maryboye show

# kubectl
kubectl_version: "v1.10.1"
kubectl_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
kubectl_darwin_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/darwin/amd64/kubectl"

# kops
kops_version: "1.9.0"
kops_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64"
kops_darwin_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-darwin-amd64"

# controller-user
remote_controller_user: olaolu
remote_controller_group: olaolu


# virtenv
controller_python_virtenv: "/usr/local/bin/{{app_name}}/python/venv"
controller_python3_virtenv: "/usr/local/bin/{{app_name}}/python3/venv"

# ssh users
my_ssh_users:
  - name: kilo
    # key: "{{ (lookup'file', 'vivek.pub') }}"
    uid: 000101
    comment: Name- Kilo Geti
  - name: bran
    # key: "{{ lookup('file', 'tom.pub') }}"
    uid: 000102    
    comment: Name- Bran Valvedi
  - name: sydney
    # key: "{{ lookup('file', 'wendy.pub') }}"
    uid: 000103
    comment: Name- Sydney Smith
  - name: tyler
    # key: "{{ lookup('file', 'jerry.pub') }}"
    uid: 000104
    comment: Name- Tyler Cappelo
# ...