--- 
############################
# Setup iam_group policies for AWS
###########################
- name: Ensure group has required managed policies
  command: aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/"{{ item }}" --group-name "{{ my_iam_group }}"
  with_items:      
  - AmazonEC2FullAccess
  - AmazonRoute53FullAccess
  - AmazonS3FullAccess
  - IAMFullAccess
  - AmazonVPCFullAccess
  tags:
    - iam_group
    - iam_group_policy  
  run_once: true