--- 
  - name: Fetch the userpasswords
    debug:
      msg: "Default passwords for new users: {{userpass.stdout}}"

  - name: Debug pub key location of ssh_users list
    debug:
      msg: "Usr public key is located at: {{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}}.pub"
    tags: 
      - debug
    verbosity: 3