---
# Insert groups and their instances into host
- include_tasks: roles/inventory/tasks/insert/group.yml
  vars:
    common_module_inventory_insert_group: "{{bastion.inventory_group}}"
    
# Add all public host addresses to known_hosts
- include_tasks: roles/inventory/tasks/insert/group_into_known_hosts.yml

- include_tasks: roles/inventory/tasks/ssh_config.yml

- name: Ensure private key is prepared for connection
      command: chmod 0400 "{{ssh_private_key}}"