---
- include_tasks: roles/common/tasks/create_file.yml
  vars:
    common_file_module_become: "{{local_ansible_user}}"
    common_file_module_path: "{{playbook_dir}}/ssh.cfg"

- name: Insert ssh configuration into playbook
  become: "{{local_ansible_user}}"
  template:
    src: "{{playbook_dir}}/roles/inventory/templates/ssh.cfg.j2"
    dest: "{{playbook_dir}}/ssh.cfg"
    # validate: /usr/sbin/sshd -t -f %s
    mode: 0775
    backup: yes