---
#  to prevent clashes in dynamic variables and group/all/vars, preceed ,#module vars with 'module'
#  Do not use new keyword 'module' as start of variable name in group/vars/all
- include: mng_ec2_keys/create.yml
  vars:
    module_key_name: "{{ ec2_key_name }}"
    module_region: "{{ ec2_region }}"
    module_keys_dir: "{{ ec2_keys_dir }}"

- include: mng_route53/zone/create.yml
  vars:
    module_zone_name: "{{route53.zone.DNS}}"
    module_zone_comment: "{{route53.zone.comment}}"

- include: mng_route53/register/create.yml
  vars:
    module_zone_name: "{{route53.zone.DNS}}"
    module_record_name: "{{route53.record.subDNS}}.{{route53.zone.DNS}}"
    module_record_type: "{{route53.record.type}}"
    module_record_value: "{{ route53.record.value }}"

- include: mng_s3_bucket/create.yml
  vars:
    module_bucket_name: "{{ state_store | replace('s3://', '') }}"
    module_bucket_region: "{{ ec2_region }}"
    module_bucket_tags: "{{ s3_bucket_tags }}"
    register: myregistered_s3create_output
  # when: "not myregistered_s3create_output.stdout | search(you already own it)" 

- include: mng_s3_bucket/upload.yml
  vars:
    module_bucket_name: "{{ state_store | replace('s3://', '') }}"
    module_bucket_region: "{{ ec2_region }}"
    module_src_file: "{{ec2_keys_dir}}/{{ec2_region}}/{{ec2_key_name}}.pub"
    module_dest_file: "infra/{{ec2_region}}/{{ec2_key_name}}.pub"

- include: mng_s3_bucket/upload.yml
  vars:
    module_bucket_name: "{{ state_store | replace('s3://', '') }}"
    module_bucket_region: "{{ ec2_region }}"
    module_src_file: "{{ec2_keys_dir}}/{{ec2_region}}/{{ec2_key_name}}.pem"
    module_dest_file: "infra/{{ec2_region}}/{{ec2_key_name}}.pem"