---
  - name: Ensure groups admin and developer are added
    become: yes
    group:
      name: "{{ item }}"
      state: present
    with_items: "{{my_ssh_user_groups}}"
    tags:
      - group

  - name: Ensure sudo group exists if debian
    become: yes
    gather_facts: true
    apt:
      name: sudo
      # update_cache: yes
      state: present
    when: ansible_os_family == 'Debian'
    tags:
      - group
      - sudo