---
  - name: Ensure mkpasswd (through whois) is installed to create pasword for new users
    become: yes
    apt:
      name: whois
      # update_cache: yes
      state: present
    tags:
      - pass

  - name: Ensure mkpasswd is installed
    command: which mkpasswd
    register: result
    tags:
      - pass

  - name: Generate password to be used by user
    command: "mkpasswd --method=sha-512 {{temp_pass}}" #mkpasswd --method=sha512 --salt=vb1tLY1qiY PASSWORD
    register: encrypted_pass
    tags:
      - pass

  - name: Hand password to mng_user's create task
    set_fact:
      user_temp_encrypted_pass: "{{encrypted_pass}}"
    tags:
      - pass
