---
#  Load kernel modules
- include: roles/glusterfs/tasks/setup/load_kernel_modules.yml
  become: yes
  vars:
    gluster_module_kernel: "{{item}}"
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool

- name: Check that mount.glusterfs command runs
  command: "mount.glusterfs"
  register: myregistered_glusterfs_cmd
  ignore_errors: yes

# Install glusterfs if cmd didn't work
- include_tasks: roles/common/tasks/install_pkg.yml
  vars:
    module_pkg: gluster-server
    module_apt_key: "{{gluster_apt_key}}"
    module_repo_source: "{{gluster_repo_source}}"
  when: myregistered_glusterfs_cmd.rc == 1

