---
- name: Ensure glusterfs-server is installed on master
  block:
  - include_tasks: roles/common/tasks/install_pkg.yml
    vars:
      module_pkg: glusterfs-server
      module_apt_key: "{{glusterfs.debian.apt_key}}"
      module_repo_source: "{{glusterfs.debian.repo_source}}"
      common_module_install_become: yes
    when: ansible_distribution == 'Debian'

  - include_tasks: roles/common/tasks/install_pkg.yml
    vars:
      module_pkg: glusterfs-server
      module_repo_source: "{{glusterfs.ubuntu.ppa}}"
      common_module_install_become: yes
    when: ansible_distribution == 'Ubuntu'
  when: "'master.inventory_group' in group_names"

- name: Ensure glusterfs-client is installed on worker nodes
  block:
  - include_tasks: roles/common/tasks/install_pkg.yml
    vars:
      module_pkg: glusterfs-client
      module_apt_key: "{{glusterfs.debian.apt_key}}"
      module_repo_source: "{{glusterfs.debian.repo_source}}"
      common_module_install_become: yes
    when: ansible_distribution == 'Debian'

  - include_tasks: roles/common/tasks/install_pkg.yml
    vars:
      module_pkg: glusterfs-client
      module_repo_source: "{{glusterfs.ubuntu.ppa}}"
      common_module_install_become: yes
    when: ansible_distribution == 'Ubuntu'
  when: "'node.inventory_group' in group_names"

#  Load kernel modules
- include: roles/glusterfs/tasks/load_kernel_modules.yml
  become: yes
  vars:
    gluster_module_kernel: "{{item}}"
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool