---
#  Insert into node group inventory
- include: roles/common/tasks/mng_inventory/insert.yml
  module_line: "[{{cluster.kops_node_inventory_group}}]"
  module_description: "Node group"
  tags:
    - gluster-create

# - name: set gluster install command to run on nodes
#   set_fact:
#     mysetfact_gluster_install_cmd: "ansible-playbook -i {{ec2_py_path}} \
#             tag_Name_nodes_maryboyecluster_maryboye_org \
#              webservers.yml \
#             -u admin \
#             --private-key={{cluster.ssh_private_key}} \
#             --tags=glusterfs, install-glusterfs"

# #  Run gluster install in node group using ansible command
# - name: Run gluster install in node group using ansible command
#   command: "{{mysetfact_gluster_install_cmd}}"

#  Install gluster-server in node group using ansible command
- include: install.yml
  delegate_to: "{{cluster.kops_node_inventory_group}}"
  tags: 
    - install-gluster

#  Other setup