---
# #  Insert into node group inventory
# - include_tasks: roles/aws/tasks/mng_inventory/dynamically_populate.yml
#   vars:
#     common_module_inventory_line: "[{{kops_node_inventory_group}}]"
#     common_module_inventory_description: "Node group"
#   tags:
#     - gluster-create

- include_tasks: roles/aws/tasks/mng_inventory/dynamically_populate.yml
  vars:
    aws_module_inventory_description: "{{item.description}}"
    aws_module_inventory_group: "{{item.group}}"
  with_items:
    - { description: "Bastion group", group: "[{{kops_bastion_inventory_group}}]"}        
    - { description: "Node group", group: "[{{kops_node_inventory_group}}]"}
    - { description: "Master group", group: "[{{kops_master_inventory_group}}]"}
  tags:
    - test_env


# - name: set gluster install command to run on nodes
#   set_fact:
#     mysetfact_gluster_install_cmd: "ansible-playbook -i {{ec2_py_path}} \
#             tag_Name_nodes_maryboyecluster_maryboye_org \
#              webservers.yml \
#             -u admin \
#             --private-key={{cluster.ssh_private_key}} \
#             --tags=glusterfs, install-glusterfs"

# #  Run gluster install in node group using ansible command
# - name: Run gluster install in node group using ansible command
#   command: "{{mysetfact_gluster_install_cmd}}"

#  Install gluster-server in node group using ansible command
- include_tasks: install.yml
  delegate_to: "{{kops_node_inventory_group}}"
  tags: 
    - install-gluster

#  Other setup
#  Create bricks

# start gluster daemon