apiVersion: v1
kind: Namespace
metadata:
  name: "tiller-video-dev-team"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "tiller-video-dev-team"
  namespace: "tiller-video-dev-team"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: video_dev_team
  namespace: tiller-video-dev-team
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "tiller-binding-video_dev_team"
  namespace: "tiller-video-dev-team"
subjects:
- kind: ServiceAccount
  name: "tiller-video-dev-team"
  namespace: "tiller-video-dev-team"
roleRef:
  kind: Role
  name: video_dev_team
  apiGroup: rbac.authorization.k8s.io
---
