apiVersion: v1
kind: Namespace
metadata:
  name: "istio-system"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "tiller-monitoring-team"
  namespace: "istio-system"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-team
  namespace: istio-system
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "tiller-binding-monitoring-team"
  namespace: "istio-system"
subjects:
- kind: ServiceAccount
  name: "tiller-monitoring-team"
  namespace: "istio-system"
roleRef:
  kind: Role
  name: monitoring-team
  apiGroup: rbac.authorization.k8s.io
---
