---
  - name: Test that new user can connect via ssh
    become: "{{my_ssh_user.name}}"
    ping: ~
    tags:
      - ssh

  - name: Ensure new user can connect via ssh
    local_action: command ssh "{{my_ssh_user.name}}@{{inventory_hostname}}"
    tags:
      - ssh
