---
- name: Make ec2.py and private key executable
  file: 
    path: "{{item}}"
    mode: "ugo+x"
  with_items:
    - "{{ec2_py_path}}"
    - "{{cluster.ssh_private_key}}"

#  list out dynamic inventory
- include: roles/common/tasks/command_log/main.yml
  vars:
    module_file: "{{playbook_dir}}/log/temp/inventory_list.log.html"
    module_command_array:
      - {command: "{{playbook_dir}}/inventory/ec2.py --list", aim: "List out dynamic inventory"}
  delegate_to: 127.0.0.1

- name: Insert {{module_description}} into inventory
  lineinfile:
    path: "{{inventory_file}}"
    line: "{{module_line}}"
    state: present
    