---
##############
# Install Terraform
##############
- include_tasks: roles/common/tasks/download_pkg.yml
  vars:
    module_package: terraform
    module_darwin_url: "{{ terraform_darwin_download_path }}"
    module_linux_url: "{{ terraform_download_path }}"
  tags:
    - install-terraform