---
- include: plan.yml
  tags:
    - create
    - terraform

- name: Ensure plan is safe
  pause:
    prompt: Please ENSURE the plan is safe before you continue.
  tags:
    - create
    - terraform

- include: apply.yml
  tags:
    - create
    - terraform

- name: Ensure user wants to destroy
  pause:
    prompt: Are you sure you want to DESTROY?
  tags:
    - destroy
    - destroy-terraform

- include: destroy.yml
  tags: 
    - destroy
    - destroy-terraform

- include: update_tf/add_ebs.yml
  tags:
    - update-terraform
    - update-tf
    - create

- include: update_tf/open_sg_ports.yml
  tags:
    - update-terraform
    - update-tf
    - create