---
#  update the tf file
- include_tasks: update_tf/add_ebs.yml
  tags:
    - update-terraform
    - update-tf
    - create
    - terraform-create

# This is already covered by generated terraform
# - include_tasks: update_tf/open_sg_ports.yml
#   tags:
#     - update-terraform
#     - update-tf
#     - create
#     - terraform-create

# plan and create
- include_tasks: plan.yml
  tags:
    - create
    - terraform
    - terraform-create

# - name: Ensure plan is safe
#   pause:
#     prompt: Please ENSURE the plan is safe before you continue.
#   tags:
#     - create
#     - terraform
#     - terraform-create

- include_tasks: apply.yml
  tags:
    - create
    - terraform
    - terraform-create

- name: Ensure user wants to destroy
  pause:
    prompt: Are you sure you want to DESTROY?
  tags:
    - destroy
    - destroy-terraform

- include_tasks: destroy.yml
  tags: 
    - destroy
    - destroy-terraform