---
  - name: Check that command is properly written
    debug:
      msg: "ssh-keygen -t rsa -b 4096 -f {{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}}.pub"
    verbosity: 3

  - name: Check if public ssh key already exists
    local_action:
      module: stat
      path: "{{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}}.pub"
    register: local_ssh_key_location

  - name: Check local_ssh_key_location.stat.exists
    debug:
      msg: "local_ssh_key_location.stat.exists = {{local_ssh_key_location.stat.exists}}"
    verbosity: 4

  - name: Ensure one new ssh RSA host key is generated locally for new user
    command: "ssh-keygen -t rsa -f {{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}} -C '' -N ''"
    # args: 
      # creates:"{{lookup('env','HOME')}}/.ssh/{{my_ssh_user.name}}.pub"
    when: local_ssh_key_location.stat.exists == false
    delegate_to: 127.0.0.1
    run_once: true
