---
- name: Ensure certbot is installed (certbot depends on awscli) 
  pip:
    name: certbot

- name: Ensure certbot has proper permissions
  file:
    path: "{{role_path}}/files/certbout-route53.sh"
    mode: "u+x,g+x,o+x"

- name: Ensure letsencrypt certificate is generated
  shell: >
  sh certbot-route53.sh
  --agree-tos
  --manual-public-ip-logging-ok
  --domains {{route53.zone.DNS}}, www.{{route53.zone.DNS}}
  --email $(git config user.email)
    chdir: "{{role_path}}/files/"
    creates: "{{role_path}}/files/letsencrypt/live"