---
- name: Delete package {{helm_module_install_pkg}}
  command: >
  "helm delete 
  --purge {{helm_module_pkg_name}}
  {% if helm_use_tls==true  %}                              
  --tls 
  --tls-cert helm.cert.pem 
  --tls-key helm.key.pem
  --tls-ca-cert {{ca.cert}}
  {% if helm_module_tiller_namspace is defined || helm_module_tiller_namspace != '' %}
  --tiller-namespace {{helm_module_tiller_namspace}}
  {% else %}
  {# use current tiller-namespace #}
  --tiller-namespace {{helm_tiller_namespace}}
  {% endif %}"
####################################################
# vars:
#   helm_module_pkg_delete_name:
#   helm_module_tiller_namspace: #optional