---
- name: Set helm command
  set_fact:
    mysetfact_helm_init_cmd: "helm install \
                              --name {{helm_module_pkg_name}} \
                              {{helm_module_pkg_repo | default('stable')}}/{{helm_module_install_pkg}} \
                              {% if helm_module_pkg_version is defined || helm_module_pkg_version != '' %}
                              -- version {{helm_module_pkg_values_file}} \
                              {% endif %}
                              -- namespace {{helm_module_pkg_namespace | default('default')}} \
                              {% if helm_module_pkg_values_file is defined || helm_module_pkg_values_file != '' %}
                              -- file {{helm_module_pkg_values_file}} \
                              {% endif %}
                              {% if helm_module_pkg_settings is defined || helm_module_pkg_settings != '' %}
                              --set {{helm_module_pkg_settings}} \
                              {% endif %}
                              {% if helm_use_tls == 'true' || helm_use_tls == 'yes' %}                              
                              --tls \
                              --tls-cert helm.cert.pem \
                              --tls-key helm.key.pem \
                              --tls-ca-cert {{ca.cert}} \
                              {% endif %}                              
                              {% if helm_module_tiller_namspace is defined || helm_module_tiller_namspace != '' %}
                              --tiller-namespace {{helm_module_tiller_namspace}}
                              {% else %}
                              {# use current tiller-namespace #}
                              --tiller-namespace {{helm_tiller_namespace}}
                              {% endif %}"
- name: |   
      Install package {{helm_module_install_pkg}}
      from {{helm_module_pkg_repo | default('stable')}} repo
      with settings {{helm_module_pkg_settings | default('')}}
  command: "{{mysetfact_helm_init_cmd}}"


####################################################
# vars:
#     helm_module_pkg_name:
#     helm_module_pkg_repo:
#     helm_module_pkg_settings: #optional
#     helm_module_pkg_namespace: # optional
#     helm_module_pkg_values_file: #optional
#     helm_module_pkg_version: # optional
#     helm_module_tiller_namspace: #optional #ensure there is tiller deployment in the namespace specified