---
- name: Check if directory exists
  stat: 
    path: "{{ common_dir_module_path | dirname}}"
  register: myregistered_dir
  tags:
    - cluster-checks
    - gluster-create
    - test_env
    
- name: Ensure directory is created
  become: "{{common_dir_become | default('no')| bool}}"
  file:
    path: "{{ common_dir_module_path | dirname}}"
    state: directory
    owner: "{{local_ansible_user}}"
    group: "{{local_ansible_group}}"
    mode: "{{ common_dir_mode | default(0775)}}"
    recurse: yes
  tags:
    - cluster-checks
    - gluster-create
    - test_env
  when: myregistered_dir.stat.exists == false or myregistered_dir.stat.isdir == False

################################
# vars:
  # common_dir_module_path:
  # common_dir_mode: #(optional)
  # common_dir_become: 