---
- name: Check if file exists
  stat: 
      path: "{{ common_file_module_path}}"
  register: myregistered_file
  tags:
    - cluster-checks
    - gluster-create
    - test_env

- name: Create file
  block:
  - include_tasks: roles/common/tasks/create_dir.yml
    vars:
      common_dir_module_path: "{{common_file_module_path}}"
    tags:
      - cluster-checks
      - gluster-create
      - test_env

  - name: Ensure file exists
    become: "{{common_file_module_become | default('no') | bool}}"
    copy:
      content: ""
      dest: "{{common_file_module_path}}"
      force: no
      owner: "{{local_ansible_user}}"
      group: "{{local_ansible_group}}"
      backup: yes
      mode: 0775
    tags:
      - cluster-checks
      - gluster-create
      - test_env
  when: myregistered_file.stat.exists == false

# vars:
#   common_file_module_become:
#   common_file_module_path: