---
- include_tasks: roles/common/tasks/create_dir.yml
  vars:
    common_dir_module_path: "{{common_file_module_path}}"

- name: Ensure file exists
  become: "{{common_file_module_become | default('no') | bool}}"
  file:
    path: "{{common_file_module_path}}"
    state: touch
    owner: "{{local_ansible_user}}"
    group: "{{local_ansible_group}}"
    mode: "{{ common_file_mode | default(0775)}}"

##############################################
# vars:
#   common_file_module_become:
#   common_file_module_path:
#   common_file_mode: