---
# - name: Configure dpkg
#   become: yes
#   command: dpkg –configure -a

# - name: Fix broken packages
#   become: yes
#   command: apt-get install -f

- name: Installing packages from an array
  block:
  - name: Ensure {{module_pkg}} gpg key is added to apt
    apt_key:
      url: "{{module_apt_key}}"
      state: present
    when: module_apt_key is defined

  - name: Ensure addition of package source
    apt_repository:
      repo: "{{module_repo_source}}"
      state: present
      filename: /etc/apt/sources.list.d/{{module_pkg}}.list
      # update_cache: yes
    when: module_repo_source is defined

  - name: Ensure installation of {{module_pkg}}
    apt:
      name: "{{ module_pkg }}"
      force: yes
      state: latest
      install_recommends: yes
    #   cache_valid_time: 3600
    #   update_cache: yes
    # register: apt_result
    # until: apt_result|success
    # retries: 3
    # delay: 1
    # ignore_errors: yes

  # - name: retry if needed using command apt-get update
  #   command: apt-get update
  #   when: apt_result|failed
  become: "{{common_module_install_become | default(no)}}"

