---
# Ensure a temp directory is created to place temp files
- include: roles/common/tasks/create_directory.yml
  vars:
    module_path: "{{role_path}}/files/tmp"

#  Deploy addons
- include: roles/k8s/tasks/deploy.yml
  vars:
    deployment: "{{item}}"
  with_items: 
    - kubernetes-dashboard
    - grafana
    - heapster
    - influxdb-grafana
