---
- block:
  - name: Ensure directory exists for local self-signed TLS certs.
    file:
      path: "{{ca_certs_dir}}/{{openssl_module_cert_resource}}"
      state: directory

  - name: Ensure directory exists for csr
    file:
      path: "{{ca_privkey_dir}}/{{openssl_module_cert_resource}}"
      state: directory

  - name: Generate an OpenSSL private key.
    openssl_privatekey:
      path: "{{ca_certs_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.key.pem"

  - name: Generate an OpenSSL CSR.
    openssl_csr:
      path: "{{ca_privkey_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.csr"
      privatekey_path: "{{ca_certs_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.key.pem"
      common_name: "{{openssl_module_cert_resource}}"

  - name: Generate a Self Signed OpenSSL certificate.
    openssl_certificate:
      path: "{{ca_certs_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.cert.pem"
      privatekey_path: "{{ca_certs_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.key.pem"
      csr_path: "{{ca_privkey_dir}}/{{openssl_module_cert_resource}}/{{openssl_module_cert_resource}}.csr"
      provider: selfsigned
  become: yes

# ########################################
# vars:
#   openssl_module_cert_resource: # e.g {{ansible_hostname}}, tiller, helm