---
- name: "Insert group name for {{bastion.name}} into host file"
  become: yes
  blockinfile:
    path: "{{inventory_dir}}/hosts"
    state: present
    insertafter:  
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{bastion.name}}"
    block: |

      [{{bastion.inventory_group}}]
      {{bastion.name}}
      
      [{{bastion.inventory_group}}:vars]
      ansible_connection=ssh
      ansible_ssh_private_key_file={{cluster.ssh_private_key}}
      ansible_ssh_common_args='-o IdentitiesOnly=yes'
      ansible_user={{bastion.user}}