---
# This tasks remove recreate and set Host Key insert command for a grouped host
- name: Ensure the current host key is removed
  shell: ssh-keygen -f "{{ ssh_known_hosts_file }}" -R "{{inventory_module_insert_known_hosts}}"

- name: Ensure ssh agent is added
  shell: ssh-add -L

- name: Ensure ssh agent is added
  shell: ssh-add {{cluster.ssh_private_key}}

- name: Get rsa host key of remote host 
  shell: "ssh-keyscan -H {{inventory_module_insert_known_hosts}} >>  {{ ssh_known_hosts_file }}"
  # register: myregistered_sshkey
  
# - name: Ensure hostkey is hashed 
#   shell: "ssh-keygen -H {{myregistered_sshkey.stdout}}"
#   register: myregistered_hask_key

# - name:  Ensure hashed hostkey is inserted into Knownhost file
#   blockinfile:
#     path: "{{ ssh_known_hosts_file }}" 
#     insertafter: EOF 
#     backup: yes 
#     marker_end: END 
#     marker: "# {mark ANSIBLE MANAGED BLOCK } {{inventory_module_insert_known_hosts}}"
#     marker_begin: BEGIN 
#     state: present
#     create: no 
#     block:  |
#       {{inventory_module_insert_known_hosts}} ssh-rsa {{myregistered_hask_key.stdout}} 
###########################################
# vars:
#   inventory_module_insert_known_hosts: "{{item}}"
