---
- name: Create remove and set Host Key insert command for a bastion group host
  block:
  - name: Determine that the host is a bastion
    set_fact:
      mysetfact_host_to_know: "{{bastion.name}}" 
    when: inventory_module_insert_known_hosts == bastion.inventory_hostname
  - name: Determine that the host is NOT a bastion 
    set_fact:
      mysetfact_host_to_know: "{{inventory_module_insert_known_hosts}}" 
    when: inventory_module_insert_known_hosts != bastion.inventory_hostname

- name: Ensure the current host key is removed
  shell: ssh-keygen -f "{{ ssh_known_hosts_file }}" -R "{{mysetfact_host_to_know}}"

- name: Get host key 
  shell: "ssh-keyscan -t -rsa {{mysetfact_host_to_know}}"
  register: myregistered_sshkey

- name: Ensure hostkey is hashed and inserted in the host key file 
  shell: "ssh-keygen {{myregistered_sshkey.stdout}}"
  register: myregistered_hask_key
  
- name: Ensure hostkey is added to known host file
  shell: "{{mysetfact_host_to_know}} ssh-rsa {{myregistered_hask_key.stdout}} >> {{ ssh_known_hosts_file }}"

###########################################
# vars:
#   inventory_module_insert_known_hosts: "{{item}}"
